service: redirect-example

provider:
  name: aws
  runtime: nodejs4.3

functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: examples/redirect
          method: get
          response:
            statusCodes:
              302:
                pattern: ''
                template: $input.path('$')
                headers:
                  Location: "'https://www.gorillastack.com'"
